### ISSUE TITLE
kalender kaartjes groen maken

### ISSUE THREAD

**Issue by KoopReynders** [fdnd/programma.fdnd.nl#33]
kalender items in het programma een groene kleur geven
en voor responsive ene overflow-hidden

en de huidige datum de accent kleur geven

**Comment by joostf** [comment]
Waar moet die overflow hidden?

**Comment by joostf** [comment]
Heb wat aanpassigen gedaan. checkie checkie!

Heeft de Sprit planning section een kader nodig? Of zo doen:

![image](https://user-images.githubusercontent.com/1061632/193018916-b6a1615d-7154-4542-943b-67fe5f6e1a22.png)

**Comment by joostf** [comment]
Hmm, is qua uitlijning van de content niet heel mooi, denk ik

**Comment by joostf** [comment]
Zo mooier?

<img width="1023" alt="image" src="https://user-images.githubusercontent.com/1061632/193024606-99bfe2cb-88f1-46ea-a8e1-49a26d6a9a0c.png">

**Comment by KoopReynders** [comment]
En de hoekjes van de dag kaartjes mogen wel wat minder round-corner...

**Comment by KoopReynders** [comment]
> 

Alle uitlijnen op de titel "Sprint planning"
Week1
en het eerste kaartje ook

**Comment by KoopReynders** [comment]
Dagen van de week met de datum ook 'in' het kaartje zetten. (geeft een rustiger beeld)
En de font size net zo als de grote kaders.

**Comment by KoopReynders** [comment]
Font-sizes van de dagkaartjes net zo groot als de grote kaders op de pagina.

**Comment by KoopReynders** [comment]
Is mooi geworden die kaartjes !
