### ISSUE TITLE
ID (ancor) op alle H1 en H2's

### ISSUE THREAD

**Issue by KoopReynders** [fdnd/programma.fdnd.nl#34]

**Comment by ju5tu5** [comment]
Hoe bedoel je dit? Zoals op GitHub hieronder?
<img width="268" alt="Schermafbeelding 2022-09-29 om 20 26 16" src="https://user-images.githubusercontent.com/140124/193113218-e4eb808d-c410-4baa-af4f-266c00bbd03f.png">

**Comment by KoopReynders** [comment]
gewoon

**Comment by KoopReynders** [comment]
Net zoals GH inderdaad. Dat je een ancor naar het id krijgt van alle H elementen. 
En met een -this is a linkable element- hover zou helemaal gaaf zijn, kan dat?

**Comment by ju5tu5** [comment]
Geïmplementeerd op de meeste h2 en h3 elementen, een aantal elementen komt uit prismic.io, daarvoor moeten we alle sprints door. Dit doen we op een later moment.

**Comment by ju5tu5** [comment]
Een HTML serializer schrijven voor h1 en h2 die automagisch anchors toevoegt: https://prismic.io/docs/technologies/html-serializer
