### ISSUE TITLE
Main nav menu position

### ISSUE THREAD

**Issue by KoopReynders** [fdnd/programma.fdnd.nl#37]
<img width="908" alt="image" src="https://user-images.githubusercontent.com/1391509/193413840-e97e45cd-f69a-4624-9894-0ecab7d9a645.png">

Het menu item is nogal vreemd uitgelijnd. 
lMeer naar links, of helemaal rechts?

**Comment by ju5tu5** [comment]
Er komen meer items bij, ik wil de actieve sprints in het 1e en 2e jaar naast home zetten, dan is het logischer om het zo uit te lijnen..

**Comment by KoopReynders** [comment]
Heb nu handmatig de actieve sprints toegevoegd aan Nav.svelte. 
Er gaat nog iets niet helemaal goed met de link. ```data-sveltekit-reload```
(En dit kan natuurlijk veel beter gegenereerd worden op basis van de datum)
