### ISSUE TITLE
Gele Background achter de border-radius 

### ISSUE THREAD

**Issue by Stefan-Espant** [fdnd/programma.fdnd.nl#41]
Op programma.fdnd.nl heeft de border-radius een gele bg. Klopt dat?<br>
<img width="1080" alt="Schermafbeelding 2022-10-14 om 13 09 24" src="https://user-images.githubusercontent.com/89298385/195838599-4c4cea86-8d8c-4c0e-8a84-ace5f1828158.png">

**Comment by KoopReynders** [comment]
Foutje. Bedankt!
En fixed met de nieuwe view.
