### ISSUE TITLE
toon-meer knop

### ISSUE THREAD

**Issue by KoopReynders** [fdnd/programma.fdnd.nl#51]
- Label meer-info button veranderen naar toon-meer? 
- CSS style mouse pointer toevoegen ```cursor: pointer;```
- on/off toggle knop van maken?
- Knop in het semester blok plaatsen

**Comment by KoopReynders** [comment]
toggle added

**Comment by joostf** [comment]
De state van de button staat bij entree op de pagina verkeerd om:

<img width="1396" alt="show:hide dates" src="https://github.com/fdnd/programma.fdnd.nl/assets/1061632/16742eec-8870-48f9-b83c-e8a3a9d696d6">

**Comment by KoopReynders** [comment]
Daar zijn de meningen vaak over verdeeld. Toont het button label de feedback van de huidige states, of een feedforward, de state die je gaat krijgen? 

Is het zo beter/logischer ?
<img width="342" alt="image" src="https://github.com/fdnd/programma.fdnd.nl/assets/1391509/17d7c856-114d-4c23-b1af-1bfd71b9d9e0">

<img width="343" alt="image" src="https://github.com/fdnd/programma.fdnd.nl/assets/1391509/aa2c0a81-3175-49e9-b751-1f1e5ee3f89a">

**Comment by KoopReynders** [comment]
Gedaan. (en de knop is ook alweer weggehaald, zodat je altijd de datums ziet)
