### ISSUE TITLE
Netlify build lukt niet

### ISSUE THREAD

**Issue by ju5tu5** [fdnd/programma.fdnd.nl#56]
Er is iets gekkigs, hier de error msg:
<img width="1181" alt="Scherm­afbeelding 2023-01-31 om 11 53 26" src="https://user-images.githubusercontent.com/140124/215740945-79ceefe0-9a23-4c76-bda1-e8ebae42861d.png">

**Comment by joostf** [comment]
gefikst, foutje in een formatHomepageUrl function..
