### ISSUE TITLE
Full screen not working

### ISSUE THREAD

**Issue by KoopReynders** [fdnd/programma.fdnd.nl#59]
Full screen button doet het niet.

**Comment by joostf** [comment]
Wat werkt er niet?

**Comment by KoopReynders** [comment]
Bij mij, in Safari, werkt het niet. 
(Zou handig zijn als we een Stage omgeving hebben om dit uit te testen voordat we naar producten actie gaan)

**Comment by joostf** [comment]
Er is nu een dev omgeving: https://dev-programma-fdnd.netlify.app/, build vanuit de dev branch
